name: Build and Upload Arduino Sketch

on:
  push:
    branches:
      - main

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Arduino IDE
      uses: arduino/setup-arduino@v2
      with:
        board_url: esp32:esp32
        sketch: sketch/sketch.ino

    - name: Install DHT Library
      run: arduino-cli lib install "DHT sensor library"

    - name: Install Adafruit Unified Sensor Library
      run: arduino-cli lib install "Adafruit Unified Sensor"

    - name: Build and Upload Sketch
      run: |
        arduino-cli compile --fqbn esp32:esp32 Greenhouse_control_using_esp32_and_FreeRtos.ino
        arduino-cli upload --fqbn esp32:esp32 Greenhouse_control_using_esp32_and_FreeRtos.ino