name: ESP32 Arduino CI

on:
  push:
    paths:
    - '**.ino'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install ESP32 core and libraries
      uses: arduino/setup-arduino-cli@v1
      with:
        board: esp32:esp32:esp32doit-devkit-v1
        additional_urls: |
          https://dl.espressif.com/dl/package_esp32_index.json

    - name: Compile Sketch
      run: |
        arduino-cli lib install "Adafruit Unified Sensor"
        arduino-cli lib install "DHT sensor library"
        arduino-cli compile --fqbn esp32:esp32:esp32doit-devkit-v1 ${{ github.workspace }}/Greenhouse_control_using_esp32_and_FreeRtos.ino

        